{% set name = "nbval" %}
{% set version = "0.9.2" %}
{% set sha256 = "e26ea0af4b46bc8200075fc665bf8e645aaeae1467ce6c7d84fe595402a11d3d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest
    - six
    - nbformat
    - ipykernel
    - jupyter_client
    - coverage

test:
  imports:
    - nbval
  commands:
    - py.test --nbval | grep nbval-{{ version }}

about:
  home: https://github.com/computationalmodelling/nbval
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: 'A py.test plugin to validate Jupyter notebooks'

extra:
  recipe-maintainers:
    - kain88-de
    - takluyver
